export const api = {
    url: 'https://btoxxqh6lj.execute-api.sa-east-1.amazonaws.com',
    stage: 'prod',
    endpoints: {
        habitacionAll: 'habitaciones',
        habitacionOne: 'habitacion',
        tipohabitacionAll: 'tipo-habitaciones',
        tipohabitacionOne: 'tipo-habitacion',
        estadohabitacionAll: 'estado-habitaciones',
        estadohabitacionOne: 'estado-habitacion',
        nivelAll: 'niveles',
        nivelOne: 'nivel',
        tiposervicioAll: 'tipo-servicios',
        tiposervicioOne: 'tipo-servicio',
        reservaAll: 'reservas',
        reservaOne: 'reserva',
        recepcionAll: 'recepciones',
        recepcionOne: 'recepcion',
        movimientoAll: 'movimientos',
        movimientoOne: 'movimiento',
        cajaAll: 'cajas',
        cajaOne: 'caja',
        generalAll: 'generales',
        generalOne: 'general'
    },
    url_php: 'https://darkseagreen-oryx-744337.hostingersite.com',
    // url_php: 'http://localhost/hotel_api',
    api_php_create: 'create.php',
    api_php_read: 'read.php',
    api_php_update: 'update.php',
    api_php_delete: 'delete.php',
    api_php_fileUpload: 'file-upload.php',
}